### ISSUE TITLE
Kakfa's Zookeeper client is deprecated and the transport is unusable

### ISSUE THREAD

**Issue by betacar** [moleculerjs/moleculer-template-project#16]
By default, the `moleculerjs/moleculer-template-project` template adds, when selected on the installer, `kafka-node@4.1.3`. However, when running the app, the following error messages are printed and the app fails to run:
```sh
project-api    | [2019-10-26T21:52:40.547Z] INFO  176f2e702675-18/TRANSIT: Reconnecting...
project-api    | [2019-10-26T21:52:40.548Z] WARN  176f2e702675-18/TRANSPORTER: Kafka Transporter is an EXPERIMENTAL transporter. Do NOT use it in production yet!
project-api    | [2019-10-26T21:52:40.549Z] WARN  176f2e702675-18/TRANSIT: Connection is failed. Kafka.Client is not a constructor
project-greeter | [2019-10-26T21:52:40.642Z] INFO  8f46b2998c91-17/TRANSIT: Reconnecting...
project-greeter | [2019-10-26T21:52:40.642Z] WARN  8f46b2998c91-17/TRANSPORTER: Kafka Transporter is an EXPERIMENTAL transporter. Do NOT use it in production yet!
project-greeter | [2019-10-26T21:52:40.643Z] WARN  8f46b2998c91-17/TRANSIT: Connection is failed. Kafka.Client is not a constructor
```

This is because the [Moleculer Kafka transporter](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/kafka.js#L92) uses the `Kafka.Client` module, which was deprecated on `kafka-node@4.0.0`.

**Comment by betacar** [comment]
IMHO, there are two solutions available:
1. Patch the template and revert `kafka-node`'s upgrade to `4.1.3` on https://github.com/moleculerjs/moleculer-template-project/commit/0e4190c692f6783a6ef8c8059a11670a3e191288, back to `3.0.1` on https://github.com/moleculerjs/moleculer-template-project/commit/65ec399 .
2. Update the Kafka transporter on `moleculerjs/moleculer` to not use the Zookeeper client.

Edit: a word.

**Comment by intech** [comment]
Hm. Thank you for your comment. I will double-check it again today.
When upgrading to version 4, everything worked for me without errors.

**Comment by icebob** [comment]
kafka-node is updated in the 0.14 of Moleculer and it will be released in some days.
