### ISSUE TITLE
How can we call another action which is present in 2nd node  from 1st node ?

### ISSUE THREAD

**Issue by meghnamishraa** [moleculerjs/moleculer-template-project#21]
hey all. How can we call another action which is present in 2nd node  from 1st node ?

**Comment by AndreMaz** [comment]
`ctx.call("serviceName.actionName")`

PS: for questions please use [Discord chat](https://discord.gg/TSEcDRP)

**Comment by meghnamishraa** [comment]
But I think we will do that from one node only. But I have 2 nodes and I want to call 2nd node action from 1st node without any api call?

**Comment by AndreMaz** [comment]
Services can be [local](https://moleculer.services/docs/0.14/concepts.html#Local-Services) or [remote](https://moleculer.services/docs/0.14/concepts.html#Remote-Services) but it doesn't matter... You call them with `ctx.call("serviceName.actionName")` and moleculer handles the rest.

Anyway, you might check the [Core Concepts page](https://moleculer.services/docs/0.14/concepts.html) or, if you prefer, a [video tutorial](https://www.youtube.com/watch?v=t4YR6MWrugw) that explains how things work
