### ISSUE TITLE
Doesn't work behind a corporate proxy

### ISSUE THREAD

**Issue by brendon-flanagan** [moleculerjs/moleculer-template-project#29]
How do you use this behind a corporate proxy ?
I've tried cntlm, but it still does not work when trying to init a new project.

init project moleculer-demo
Template repo: moleculerjs/moleculer-template-project
Downloading template...
Failed to download repo from 'moleculerjs/moleculer-template-project'!

**Comment by wololo-aeyoyo** [comment]
same issue over here, did you find any solution?

**Comment by intech** [comment]
@brendon-flanagan @wololo-aeyoyo download repo and use local path for template https://moleculer.services/docs/0.14/moleculer-cli.html#Local-Templates
